import { useState, useEffect } from 'react';

export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'mr', name: 'मराठी (Marathi)' },
  { code: 'hi', name: 'हिंदी (Hindi)' },
  { code: 'ta', name: 'தமிழ் (Tamil)' },
  { code: 'te', name: 'తెలుగు (Telugu)' },
  { code: 'kn', name: 'ಕನ್ನಡ (Kannada)' },
  { code: 'ml', name: 'മലയാളം (Malayalam)' },
  { code: 'gu', name: 'ગુજરાતી (Gujarati)' },
  { code: 'bn', name: 'বাংলা (Bengali)' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ (Punjabi)' },
  { code: 'de', name: 'Deutsch (German)' },
  { code: 'es', name: 'Español (Spanish)' },
  { code: 'fr', name: 'Français (French)' },
  { code: 'ar', name: 'العربية (Arabic)' }
];

export function getStoredLanguage() {
  return localStorage.getItem('smartpo_web_language') || 'en';
}

export function setStoredLanguage(langCode) {
  localStorage.setItem('smartpo_web_language', langCode);
  window.dispatchEvent(new Event('smartpo_language_changed'));
}

export function useLanguage() {
  const [lang, setLang] = useState(getStoredLanguage());

  useEffect(() => {
    const handleLangChange = () => {
      setLang(getStoredLanguage());
    };
    window.addEventListener('smartpo_language_changed', handleLangChange);
    return () => window.removeEventListener('smartpo_language_changed', handleLangChange);
  }, []);

  return [lang, (newLang) => setStoredLanguage(newLang)];
}

const TRANSLATIONS = {
  en: {
    home: 'Home',
    catalog: 'Catalog',
    orders: 'Orders',
    ai_assistant: 'AI Assistant',
    profile: 'Profile',
    create_new_po: 'Create New PO',
    welcome_title: 'Welcome to SmartPO',
    search_catalog: 'Search categories or items...',
    total_orders: 'Total Orders',
    catalog_products: 'Catalog Products',
    customer_name: 'Customer Name',
    company_name: 'Company Name',
    phone_number: 'Phone Number',
    edit_profile: 'Edit Profile',
    edit_profile_desc: 'Change your full name, company, and phone',
    app_language: 'App Language',
    change_password: 'Change Password',
    change_password_desc: 'Update your security credentials',
    privacy_policy: 'Privacy Policy',
    privacy_desc: 'Understand how we protect your data',
    terms_conditions: 'Terms & Conditions',
    terms_desc: 'Review our rules and service agreement',
    logout: 'Logout',
    company: 'Company'
  },
  mr: {
    home: 'मुख्य पृष्ठ (Home)',
    catalog: 'कॅटलॉग (Catalog)',
    orders: 'ऑर्डर्स (Orders)',
    ai_assistant: 'एआय सहाय्यक',
    profile: 'प्रोफाइल',
    create_new_po: 'नवीन ऑर्डर तयार करा',
    welcome_title: 'स्मार्ट पीओ मध्ये आपले स्वागत आहे',
    search_catalog: 'श्रेणी किंवा वस्तू शोधा (Search)...',
    total_orders: 'एकूण ऑर्डर्स',
    catalog_products: 'कॅटलॉग उत्पादने',
    customer_name: 'ग्राहकाचे नाव',
    company_name: 'कंपनीचे नाव',
    phone_number: 'फोन नंबर',
    edit_profile: 'प्रोफाइल संपादित करा',
    edit_profile_desc: 'नाव, कंपनी आणि फोन बदला',
    app_language: 'ॲप भाषा (Language)',
    change_password: 'पासवर्ड बदला',
    change_password_desc: 'सुरक्षा क्रेडेन्शियल्स अपडेट करा',
    privacy_policy: 'गोपनीयता धोरण (Privacy Policy)',
    privacy_desc: 'आम्ही तुमचा डेटा कसा सुरक्षित ठेवतो',
    terms_conditions: 'नियम व अटी (Terms)',
    terms_desc: 'अटी आणि सेवा कराराचे पुनरावलोकन करा',
    logout: 'लॉग आउट',
    company: 'कंपनी'
  },
  hi: {
    home: 'होम (Home)',
    catalog: 'कैटलॉग (Catalog)',
    orders: 'ऑर्डर्स (Orders)',
    ai_assistant: 'एआई सहायक',
    profile: 'प्रोफाइल',
    create_new_po: 'नया ऑर्डर बनाएं',
    welcome_title: 'स्मार्ट पीओ में आपका स्वागत है',
    search_catalog: 'श्रेणियाँ या आइटम खोजें...',
    total_orders: 'कुल ऑर्डर्स',
    catalog_products: 'कैटलॉग उत्पाद',
    customer_name: 'ग्राहक का नाम',
    company_name: 'कंपनी का नाम',
    phone_number: 'फोन नंबर',
    edit_profile: 'प्रोफ़ाइल संपादित करें',
    edit_profile_desc: 'अपना नाम, कंपनी और फोन बदलें',
    app_language: 'ऐप की भाषा',
    change_password: 'पासवर्ड बदलें',
    change_password_desc: 'सुरक्षा क्रेडेंशियल अपडेट करें',
    privacy_policy: 'गोपनीयता नीति',
    privacy_desc: 'समझें कि हम आपके डेटा की सुरक्षा कैसे करते हैं',
    terms_conditions: 'नियम और शर्तें',
    terms_desc: 'हमारे नियमों और सेवा अनुबंध की समीक्षा करें',
    logout: 'लॉग आउट',
    company: 'कंपनी'
  },
  ta: {
    home: 'முகப்பு (Home)',
    catalog: 'பட்டியல் (Catalog)',
    orders: 'ஆணைகள் (Orders)',
    ai_assistant: 'AI உதவி',
    profile: 'சுயவிவரம்',
    create_new_po: 'புதிய ஆணை உருவாக்கவும்',
    welcome_title: 'ஸ்மார்ட் PO உங்களை வரவேற்கிறது',
    search_catalog: 'பொருட்களைத் தேடுங்கள்...',
    total_orders: 'மொத்த ஆணைகள்',
    catalog_products: 'பொருட்கள் பட்டியல்',
    customer_name: 'வாடிக்கையாளர் பெயர்',
    company_name: 'நிறுவனத்தின் பெயர்',
    phone_number: 'தொலைபேசி எண்',
    edit_profile: 'சுயவிவரத்தை திருத்து',
    edit_profile_desc: 'விவரங்களை மாற்றவும்',
    app_language: 'செயலி மொழி',
    change_password: 'கடவுச்சொல்லை மாற்றவும்',
    change_password_desc: 'பாதுகாப்பு விவரங்களை புதுப்பிக்கவும்',
    privacy_policy: 'தனியுரிமைக் கொள்கை',
    privacy_desc: 'நாங்கள் உங்கள் தரவை எவ்வாறு பாதுகாக்கிறோம்',
    terms_conditions: 'விதிமுறைகள் & நிபந்தனைகள்',
    terms_desc: 'சேவை ஒப்பந்தத்தை மதிப்பாய்வு செய்யவும்',
    logout: 'வெளியேறு',
    company: 'நிறுவனம்'
  },
  te: {
    home: 'హోమ్ (Home)',
    catalog: 'కెటలాగ్ (Catalog)',
    orders: 'ఆర్డర్లు (Orders)',
    ai_assistant: 'AI సహాయకుడు',
    profile: 'ప్రొఫైల్',
    create_new_po: 'కొత్త ఆర్డర్ సృష్టించండి',
    welcome_title: 'స్మార్ట్ PO కి స్వాగతం',
    search_catalog: 'ఉత్పత్తులను వెతకండి...',
    total_orders: 'మొత్తం ఆర్డర్లు',
    catalog_products: 'కెటలాగ్ ఉత్పత్తులు',
    customer_name: 'వినియోగదారుని పేరు',
    company_name: 'సంస్థ పేరు',
    phone_number: 'ఫోన్ నంబర్',
    edit_profile: 'ప్రొఫైల్ సవరించండి',
    edit_profile_desc: 'మీ వివరాలను మార్చండి',
    app_language: 'యాప్ భాష',
    change_password: 'పాస్‌వర్డ్ మార్చండి',
    change_password_desc: 'భద్రతా వివరాలను నవీకరించండి',
    privacy_policy: 'గోప్యతా విధానం',
    privacy_desc: 'డేటా రక్షణ వివరాలు',
    terms_conditions: 'నిబంధనలు & షరతులు',
    terms_desc: 'సేవా ఒప్పందాన్ని సమీక్షించండి',
    logout: 'లాగ్ అవుట్',
    company: 'సంస్థ'
  },
  kn: {
    home: 'ಹೋಮ್ (Home)',
    catalog: 'ಕ್ಯಾಟಲಾಗ್ (Catalog)',
    orders: 'ಆದೇಶಗಳು (Orders)',
    ai_assistant: 'AI ಸಹಾಯಕ',
    profile: 'ಪ್ರೊಫೈಲ್',
    create_new_po: 'ಹೊಸ ಆದೇಶ ರಚಿಸಿ',
    welcome_title: 'ಸ್ಮಾರ್ಟ್ PO ಗೆ ಸ್ವಾಗತ',
    search_catalog: 'ಉತ್ಪನ್ನಗಳನ್ನು ಹುಡುಕಿ...',
    total_orders: 'ಒಟ್ಟು ಆದೇಶಗಳು',
    catalog_products: 'ಕ್ಯಾಟಲಾಗ್ ಉತ್ಪನ್ನಗಳು',
    customer_name: 'ಗ್ರಾಹಕರ ಹೆಸರು',
    company_name: 'ಸಂಸ್ಥೆಯ ಹೆಸರು',
    phone_number: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    edit_profile: 'ಪ್ರೊಫೈಲ್ ತಿದ್ದುಪಡಿ ಮಾಡಿ',
    edit_profile_desc: 'ವಿವರಗಳನ್ನು ಬದಲಾಯಿಸಿ',
    app_language: 'ಆಪ್ ಭಾಷೆ',
    change_password: 'ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಿ',
    change_password_desc: 'ಸುರಕ್ಷತಾ ವಿವರ ನವೀಕರಿಸಿ',
    privacy_policy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    privacy_desc: 'ಡೇಟಾ ರಕ್ಷಣೆ ವಿವರ',
    terms_conditions: 'ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು',
    terms_desc: 'ಸೇವಾ ಒಪ್ಪಂದ ಪರಿಶೀಲಿಸಿ',
    logout: 'ಲಾಗ್ ಔಟ್',
    company: 'ಸಂಸ್ಥೆ'
  },
  de: {
    home: 'Startseite (Home)',
    catalog: 'Katalog (Catalog)',
    orders: 'Bestellungen (Orders)',
    ai_assistant: 'KI-Assistent',
    profile: 'Profil',
    create_new_po: 'Neuer Auftrag',
    welcome_title: 'Willkommen bei SmartPO',
    search_catalog: 'Kategorien oder Artikel suchen...',
    total_orders: 'Gesamte Bestellungen',
    catalog_products: 'Katalogprodukte',
    customer_name: 'Kundenname',
    company_name: 'Firmenname',
    phone_number: 'Telefonnummer',
    edit_profile: 'Profil bearbeiten',
    edit_profile_desc: 'Name, Firma und Telefonnummer ändern',
    app_language: 'App-Sprache',
    change_password: 'Passwort ändern',
    change_password_desc: 'Sicherheitsanmeldedaten aktualisieren',
    privacy_policy: 'Datenschutz-Bestimmungen',
    privacy_desc: 'Erfahren Sie, wie wir Ihre Daten schützen',
    terms_conditions: 'Allgemeine Geschäftsbedingungen',
    terms_desc: 'Überprüfen Sie unsere Regeln und Vereinbarungen',
    logout: 'Abmelden',
    company: 'Firma'
  },
  es: {
    home: 'Inicio',
    catalog: 'Catálogo',
    orders: 'Pedidos',
    ai_assistant: 'Asistente IA',
    profile: 'Perfil',
    create_new_po: 'Crear nueva OC',
    welcome_title: 'Bienvenido a SmartPO',
    search_catalog: 'Buscar categorías o artículos...',
    total_orders: 'Pedidos totales',
    catalog_products: 'Productos del catálogo',
    customer_name: 'Nombre del cliente',
    company_name: 'Nombre de la empresa',
    phone_number: 'Número de teléfono',
    edit_profile: 'Editar perfil',
    edit_profile_desc: 'Cambiar nombre, empresa y teléfono',
    app_language: 'Idioma de la aplicación',
    change_password: 'Cambiar contraseña',
    change_password_desc: 'Actualizar credenciales de seguridad',
    privacy_policy: 'Política de privacidad',
    privacy_desc: 'Comprenda cómo protegemos sus datos',
    terms_conditions: 'Términos y condiciones',
    terms_desc: 'Revise nuestras normas y acuerdos',
    logout: 'Cerrar sesión',
    company: 'Empresa'
  },
  fr: {
    home: 'Accueil',
    catalog: 'Catalogue',
    orders: 'Commandes',
    ai_assistant: 'Assistant IA',
    profile: 'Profil',
    create_new_po: 'Créer un bon de commande',
    welcome_title: 'Bienvenue sur SmartPO',
    search_catalog: 'Rechercher des articles...',
    total_orders: 'Commandes totales',
    catalog_products: 'Produits du catalogue',
    customer_name: 'Nom du client',
    company_name: 'Nom de l\'entreprise',
    phone_number: 'Numéro de téléphone',
    edit_profile: 'Modifier le profil',
    edit_profile_desc: 'Changer de nom, entreprise et téléphone',
    app_language: 'Langue de l\'application',
    change_password: 'Changer le mot de passe',
    change_password_desc: 'Mettre à jour la sécurité',
    privacy_policy: 'Politique de confidentialité',
    privacy_desc: 'Comment nous protégeons vos données',
    terms_conditions: 'Conditions générales',
    terms_desc: 'Consulter nos conditions de service',
    logout: 'Se déconnecter',
    company: 'Entreprise'
  }
};

export function t(key, langCode = getStoredLanguage()) {
  return TRANSLATIONS[langCode]?.[key] || TRANSLATIONS['en']?.[key] || key;
}
